### ISSUE TITLE
Google App Engine Deployment

### ISSUE THREAD

**Issue by alexthomas93** [zmap/zdns#152]
Hi I've been trying to deploy zdns to a Google App Engine flexible environment but am running into the following issue during deployment:
```shell
Step 3/5 : RUN go get   github.com/zmap/zdns/zdns       cloud.google.com/go/pubsub         google.golang.org/appengine  golang.org/x/net/context        cloud.google.com/go/storage
```
Results in
```shell
# github.com/miekg/dns
../github.com/miekg/dns/msg_helpers.go:144: base32.HexEncoding.WithPadding undefined (type *base32.Encoding has no field or method WithPadding)
../github.com/miekg/dns/msg_helpers.go:144: undefined: base32.NoPadding
The command '/bin/sh -c go get  github.com/zmap/zdns/zdns       cloud.google.com/go/pubsub         google.golang.org/appengine  golang.org/x/net/context   cloud.google.com/go/storage' returned a non-zero code: 2
ERROR
ERROR: build step 0 "gcr.io/cloud-builders/docker" failed: exit status 2
```
https://github.com/miekg/dns/issues/687 and https://github.com/caffix/amass/issues/39 suggest the issue is to do with the version of Go used by App Engine. As the most up to date version of Go supported by App Engine is 1.8 I am not able to use versions 1.9 or 1.10. Is there anything else I could do to get zdns working with Go version 1.8?

**Comment by alexthomas93** [comment]
I have found a work around to run newer versions of Go on App Engine so I have closed the ticket.
