### ISSUE TITLE
zdns does not build on darwin

### ISSUE THREAD

**Issue by paul-pearce** [zmap/zdns#316]
Currently zdns does not build on darwin (go1.17.6):

```
$: git reset --hard HEAD
HEAD is now at 7430d80 Added zdns paper ref to readme (#313)
$: go build
# github.com/zmap/zdns/pkg/zdns
./zdns.go:191:3: undefined: ulimit_check
./zdns.go:193:3: undefined: ulimit_check
$:
```

The issue is `pkg/zdns/ulimit_check_linux.go`'s filename. The file name suffix _linux appears to be overriding the build constraint directives in the file that specify it is also applicable for darwin, so go build is ignoring this file. The secondary file, ulimit_check.go has a no darwin directive, thus zdns won't build. If you rename the file to literally anything else, it works.

PR coming shortly.

**Comment by paul-pearce** [comment]
Addressed in PR #317

**Comment by paul-pearce** [comment]
Fixed and merged
